_parent_: projects/splatting/configs/base.yaml
data:
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 1.0
    root: data/cecum_t1_a
    train:
        image_size:
        - 300
        - 375
    type: projects.splatting.splatter.data
    val:
        image_size:
        - 300
        - 375
model:
    appear_embed:
        enabled: true
    object:
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 4
            mlp:
                inside_out: false
